version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install --save jquery bootstrap-vue
      - npm install --save jquery bootstrap-vue
  build:
    commands:
      - npm run build
    base-directory: dist  
artifacts:
  files:
    - '**/*'